lints:
  image: ghcr.io/cirruslabs/flutter
  before_script:
    - cd todoappflutter
  stage: lints
  script:
    - flutter analyze
android:
  image: ghcr.io/cirruslabs/flutter
  before_script:
    - cd todoappflutter
  stage: build-flutter
  script:
    - flutter build apk --release --build-number ${CI_JOB_ID:0:8}
  artifacts:
    paths:
      - todoappflutter/build/app/outputs/flutter-apk/app-release.apk
