image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    # or with yarn:
    #- .yarn

stages:
  - build

before_script:
  - cd ToDoApp
  - npm ci --cache .npm
  # or with yarn:
  #- yarn install --cache-folder .yarn

eas-build:
  stage: build
  variables:
    EAS_NO_VCS: 1
  script:
    - apk add --no-cache bash
    - npx eas-cli build --platform android --profile preview --non-interactive --no-wait